/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ControlType {
  None = 0,
  RelAxis = 1 << 0,
  AbsAxis = 1 << 1,
  PushButton = 1 << 2,
  ToggleButton = 1 << 3,
  Pov = 1 << 4
}
